# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: vote
#   name: vote
# spec:
#   type: NodePort
#   ports:
#   - name: "vote-service"
#     port: 5000
#     targetPort: 80
#     nodePort: 31002
#   selector:
#     app: vote
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  selector:
    app: vote
  ports:
    - port: 5000
      targetPort: 80
  type: LoadBalancer